<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SiliconLife.Core\SiliconLife.Core.csproj" />
    <ProjectReference Include="..\SiliconLife.Common\SiliconLife.Common.csproj" />
    <ProjectReference Include="..\SiliconLife.Speedy\SiliconLife.Speedy.csproj" />
    <ProjectReference Include="..\SiliconLife.Speedy.Manager\SiliconLife.Speedy.Manager.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>slc.ico</ApplicationIcon>
    <Company>Hoshino Kennji</Company>
  </PropertyGroup>

  <Import Project="SiliconLife.Fast.csproj.targets" Condition="Exists('SiliconLife.Fast.csproj.targets')" />
</Project>
