<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SiliconLife.Core\SiliconLife.Core.csproj" />
    <ProjectReference Include="..\SiliconLife.Common\SiliconLife.Common.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>slc.ico</ApplicationIcon>
    <Company>Hoshino Kennji</Company>
  </PropertyGroup>

</Project>
