// Copyright (c) 2026 Hoshino Kennji
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using SiliconLife.Default.Web.Models;

namespace SiliconLife.Default.Web.Views;

public class PermissionView : ViewBase
{
    public override string Render(object model)
    {
        var vm = model as PermissionViewModel;
        if (vm == null) return string.Empty;
        var body = RenderBody(vm);
        return RenderPage(vm.Skin, vm.Localization.PageTitlePermission, "permissions", vm.Localization, body, GetScripts(vm.Localization, vm.BeingId), GetStyles(), helpTopicId: "permission");
    }

    private static H RenderBody(PermissionViewModel vm)
    {
        return H.Div(
            H.Div(
                H.A("← " + vm.Localization.BeingsBackToList).Href("/beings").Class("permission-back-link"),
                H.H1(string.Format(vm.Localization.PermissionPageHeader, vm.BeingId.ToString()))
            ).Class("page-header"),
            H.Div(
                CodeEditorView.RenderWidget(
                    "permissionCallbackEditor",
                    vm.CurrentCallbackCode ?? "",
                    "csharp",
                    $"Permission Callback - Being {vm.BeingId}",
                    readOnly: false,
                    theme: "vs-dark",
                    minimap: true,
                    lineNumbers: true,
                    wordWrap: true,
                    saveEndpoint: $"/api/permissions/save?beingId={vm.BeingId}"
                )
            ).Class("card editor-fill-height"),
            // Loading indicator
            H.Div(
                H.Div("").Class("loading-spinner"),
                H.Div("Loading...").Class("loading-text")
            ).Id("loading-indicator").Class("loading-indicator")
        ).Class("page-content flex-column no-scroll");
    }

    private static JsSyntax GetScripts(DefaultLocalizationBase loc, Guid beingId)
    {
        // Use scripts generated by CodeEditorView
        var editorScripts = CodeEditorView.GetWidgetScripts(
            "permissionCallbackEditor",
            "csharp",
            "vs-dark",
            readOnly: false,
            minimap: true,
            lineNumbers: true,
            wordWrap: true,
            saveEndpoint: $"/api/permissions/save?beingId={beingId}"
        );

        // Add loading indicator control functions
        var showLoadingBody = Js.Block()
            .Add(() => Js.Const(() => "indicator", () => Js.Id(() => "document").Call(() => "getElementById", () => Js.Str(() => "loading-indicator"))))
            .Add(() => Js.If(() => new List<(JsSyntax?, List<JsSyntax>)>
            {
                { (Js.Id(() => "indicator"), new List<JsSyntax>
                    {
                        Js.Id(() => "indicator").Prop(() => "classList").Call(() => "add", () => Js.Str(() => "active")).Stmt()
                    }
                )}
            }));

        var hideLoadingBody = Js.Block()
            .Add(() => Js.Const(() => "indicator", () => Js.Id(() => "document").Call(() => "getElementById", () => Js.Str(() => "loading-indicator"))))
            .Add(() => Js.If(() => new List<(JsSyntax?, List<JsSyntax>)>
            {
                { (Js.Id(() => "indicator"), new List<JsSyntax>
                    {
                        Js.Id(() => "indicator").Prop(() => "classList").Call(() => "remove", () => Js.Str(() => "active")).Stmt()
                    }
                )}
            }));

        return Js.Block()
            .Add(() => editorScripts)
            .Add(() => Js.Func(() => "showLoading", () => new List<string>(), () => showLoadingBody))
            .Add(() => Js.Func(() => "hideLoading", () => new List<string>(), () => hideLoadingBody));
    }

    private static CssBuilder GetStyles()
    {
        // Use styles provided by CodeEditorView + custom adaptive height styles
        return CodeEditorView.GetWidgetStyles()
            .Selector(".page-header")
                .Property("margin-bottom", "20px")
            .EndSelector()
            .Selector(".permission-back-link")
                .Property("display", "inline-block")
                .Property("margin-bottom", "12px")
                .Property("color", "var(--accent-primary)")
                .Property("text-decoration", "none")
                .Property("font-size", "14px")
                .Property("transition", "color 0.2s")
            .EndSelector()
            .Selector(".permission-back-link:hover")
                .Property("color", "var(--accent-secondary, var(--accent-primary))")
                .Property("text-decoration", "underline")
            .EndSelector()
            .Selector(".page-content.flex-column")
                .Property("display", "flex")
                .Property("flex-direction", "column")
                .Property("overflow-y", "hidden")
                .Property("height", "100%")
            .EndSelector()
            .Selector(".page-content.no-scroll")
                .Property("overflow-y", "hidden")
            .EndSelector()
            .Selector(".card.editor-fill-height")
                .Property("flex", "1")
                .Property("display", "flex")
                .Property("flex-direction", "column")
                .Property("min-height", "0")
                .Property("overflow", "hidden")
            .EndSelector()
            .Selector(".code-editor-widget")
                .Property("flex", "1")
                .Property("min-height", "0")
                .Property("display", "flex")
                .Property("flex-direction", "column")
            .EndSelector()
            .Selector(".code-editor-container")
                .Property("flex", "1")
                .Property("min-height", "0")
                .Property("height", "auto")
            .EndSelector()
            // Loading indicator styles
            .Selector(".loading-indicator")
                .Property("display", "none")
                .Property("flex-direction", "column")
                .Property("align-items", "center")
                .Property("justify-content", "center")
                .Property("padding", "40px 20px")
                .Property("color", "var(--text-secondary)")
                .Property("gap", "16px")
            .EndSelector()
            .Selector(".loading-indicator.active")
                .Property("display", "flex")
            .EndSelector()
            .Selector(".loading-spinner")
                .Property("width", "40px")
                .Property("height", "40px")
                .Property("border", "3px solid var(--border-color)")
                .Property("border-top-color", "var(--accent-color)")
                .Property("border-radius", "50%")
                .Property("animation", "spin 1s linear infinite")
            .EndSelector()
            .Keyframes("spin", kf => kf
                .At("0%", p => p.Property("transform", "rotate(0deg)"))
                .At("100%", p => p.Property("transform", "rotate(360deg)")))
            .Selector(".loading-text")
                .Property("font-size", "14px")
                .Property("font-weight", "500")
            .EndSelector();
    }
}
